#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  May 19, 2023 04:32:38 PM EDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m70" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x700+504+22
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1900 1200
    wm minsize $top 120 120
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Product Development Cycle Tester"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    labelframe "$top.lab47" \
        \
        -font "-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -text "Move Linear Relative" \
        -background $vTcl(actual_gui_bg) -height 135 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 550 
    vTcl:DefineAlias "$top.lab47" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.lab47
    labelframe "$site_3_0.lab48" \
        \
        -font "-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -text "Bump Back" \
        -background $vTcl(actual_gui_bg) -height 101 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 220 
    vTcl:DefineAlias "$site_3_0.lab48" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.lab48
    button "$site_4_0.but53" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonLin(-50)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "50" 
    vTcl:DefineAlias "$site_4_0.but53" "buttonBk50" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite backwards move 50mm relitive}
    }
    vTcl:copy_lock $site_4_0.but53
    button "$site_4_0.but54" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonLin(-10)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "10" 
    vTcl:DefineAlias "$site_4_0.but54" "buttonBk10" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite backwards move 10mm relitive}
    }
    vTcl:copy_lock $site_4_0.but54
    button "$site_4_0.but55" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonLin(-1)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "1" 
    vTcl:DefineAlias "$site_4_0.but55" "buttonBk1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite backwards move 1mm relitive}
    }
    vTcl:copy_lock $site_4_0.but55
    button "$site_4_0.but56" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -command "lambda :cb_buttonLin(float(-0.1))" -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "0.1" 
    vTcl:DefineAlias "$site_4_0.but56" "buttonBk01" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but56 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite backwards move 0.1mm relitive}
    }
    vTcl:copy_lock $site_4_0.but56
    scale "$site_4_0.sca57" \
        -activebackground $vTcl(analog_color_m) \
        -background $vTcl(actual_gui_bg) -bigincrement 0.0 \
        -command "cb_scaleLinSpeed" -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -from 0.0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -length 136 -orient horizontal -resolution 1.0 -tickinterval 0.0 \
        -to 100.0 -troughcolor #d9d9d9 
    vTcl:DefineAlias "$site_4_0.sca57" "scaleLinSpeed" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.sca57
    label "$site_4_0.lab59" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Speed" 
    vTcl:DefineAlias "$site_4_0.lab59" "Label1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.lab59
    place $site_4_0.but53 \
        -in $site_4_0 -x 10 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but54 \
        -in $site_4_0 -x 60 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but55 \
        -in $site_4_0 -x 110 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but56 \
        -in $site_4_0 -x 160 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.sca57 \
        -in $site_4_0 -x 40 -y 45 -width 120 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab59 \
        -in $site_4_0 -x 5 -y 65 -width 34 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab48
    labelframe "$site_3_0.lab62" \
        \
        -font "-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -text "Bump Forward" \
        -background $vTcl(actual_gui_bg) -height 101 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 220 
    vTcl:DefineAlias "$site_3_0.lab62" "Labelframe2_1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.lab62
    button "$site_4_0.but53" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -command "lambda :cb_buttonLin(float(0.1))" -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "0.1" 
    vTcl:DefineAlias "$site_4_0.but53" "buttonFw01" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite forewards move 0.1mm relitive}
    }
    vTcl:copy_lock $site_4_0.but53
    button "$site_4_0.but54" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonLin(1)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "1" 
    vTcl:DefineAlias "$site_4_0.but54" "buttonFw1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite forewards move 1mm relitive}
    }
    vTcl:copy_lock $site_4_0.but54
    button "$site_4_0.but55" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonLin(10)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "10" 
    vTcl:DefineAlias "$site_4_0.but55" "buttonFw10" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite forewards move 10mm relitive}
    }
    vTcl:copy_lock $site_4_0.but55
    button "$site_4_0.but56" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonLin(50)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "50" 
    vTcl:DefineAlias "$site_4_0.but56" "buttonFw50" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but56 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite forewards move 50mm relitive}
    }
    vTcl:copy_lock $site_4_0.but56
    button "$site_4_0.but97" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonHome('LIN')" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Home" 
    vTcl:DefineAlias "$site_4_0.but97" "buttonLinHome" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_0.but53 \
        -in $site_4_0 -x 10 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but54 \
        -in $site_4_0 -x 60 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but55 \
        -in $site_4_0 -x 110 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but56 \
        -in $site_4_0 -x 160 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but97 \
        -in $site_4_0 -x 80 -y 60 -width 47 -height 24 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab62
    button "$site_3_0.but63" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_stop" -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "STOP" 
    vTcl:DefineAlias "$site_3_0.but63" "buttonLinStop" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.but63
    place $site_3_0.lab48 \
        -in $site_3_0 -x 10 -y 23 -width 220 -relwidth 0 -height 101 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 320 -y 20 -width 220 -height 101 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but63 \
        -in $site_3_0 -x 240 -y 30 -width 70 -relwidth 0 -height 60 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.lab47
    frame "$top.fra49" \
        -borderwidth 2 -background $vTcl(actual_gui_bg) -height 115 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 117 
    vTcl:DefineAlias "$top.fra49" "Frame1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra49
    entry "$site_3_0.ent51" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable "absolutePos" -width 44 
    vTcl:DefineAlias "$site_3_0.ent51" "EntryAbsPos" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    entry "$site_3_0.ent52" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable "absoluteRot" -width 44 
    vTcl:DefineAlias "$site_3_0.ent52" "EntryAbsRot" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab64" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Position" 
    vTcl:DefineAlias "$site_3_0.lab64" "Label2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab65" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Rotation" 
    vTcl:DefineAlias "$site_3_0.lab65" "Label3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab82" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify right -text "Absolute Location" 
    vTcl:DefineAlias "$site_3_0.lab82" "Label4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.lab82
    place $site_3_0.ent51 \
        -in $site_3_0 -x 5 -y 50 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent52 \
        -in $site_3_0 -x 60 -y 50 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 5 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 55 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.lab82 \
        -in $site_3_0 -x 0 -y 10 -width 110 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra49
    labelframe "$top.lab67" \
        \
        -font "-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -text "Move Rotation Relative" \
        -background $vTcl(actual_gui_bg) -height 135 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 550 
    vTcl:DefineAlias "$top.lab67" "Labelframe1_1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.lab67
    labelframe "$site_3_0.lab48" \
        \
        -font "-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -text "Rotate CCW" \
        -background $vTcl(actual_gui_bg) -height 101 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 220 
    vTcl:DefineAlias "$site_3_0.lab48" "Labelframe2_2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.lab48
    button "$site_4_0.but53" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonRot(-90)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "90" 
    vTcl:DefineAlias "$site_4_0.but53" "buttonCCW90" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite CCW move 90° relative}
    }
    vTcl:copy_lock $site_4_0.but53
    button "$site_4_0.but54" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonRot(-30)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "30" 
    vTcl:DefineAlias "$site_4_0.but54" "buttonCCW30" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite CCW move 30° relative}
    }
    vTcl:copy_lock $site_4_0.but54
    button "$site_4_0.but55" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonRot(-5)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "5" 
    vTcl:DefineAlias "$site_4_0.but55" "buttonCCW5" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite CCW move 5° relative}
    }
    vTcl:copy_lock $site_4_0.but55
    button "$site_4_0.but56" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonRot(-1)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "1" 
    vTcl:DefineAlias "$site_4_0.but56" "buttonCCW1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but56 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite CCW move 1° relative}
    }
    vTcl:copy_lock $site_4_0.but56
    scale "$site_4_0.sca57" \
        -activebackground $vTcl(analog_color_m) \
        -background $vTcl(actual_gui_bg) -bigincrement 0.0 \
        -command "cb_scaleRotSpeed" -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -from 0.0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -length 136 -orient horizontal -resolution 1.0 -tickinterval 0.0 \
        -to 100.0 -troughcolor #d9d9d9 
    vTcl:DefineAlias "$site_4_0.sca57" "scaleRotSpeed" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.sca57
    label "$site_4_0.lab59" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Speed" 
    vTcl:DefineAlias "$site_4_0.lab59" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.lab59
    place $site_4_0.but53 \
        -in $site_4_0 -x 8 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but54 \
        -in $site_4_0 -x 60 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but55 \
        -in $site_4_0 -x 110 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but56 \
        -in $site_4_0 -x 160 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.sca57 \
        -in $site_4_0 -x 40 -y 45 -width 120 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab59 \
        -in $site_4_0 -x 5 -y 65 -width 34 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab48
    labelframe "$site_3_0.lab62" \
        \
        -font "-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -text "Rotate CW" \
        -background $vTcl(actual_gui_bg) -height 101 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 220 
    vTcl:DefineAlias "$site_3_0.lab62" "Labelframe2_1_1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.lab62
    button "$site_4_0.but53" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonRot(1)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "1" 
    vTcl:DefineAlias "$site_4_0.but53" "buttonCW1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite CW move 1° relative}
    }
    vTcl:copy_lock $site_4_0.but53
    button "$site_4_0.but54" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonRot(5)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "5" 
    vTcl:DefineAlias "$site_4_0.but54" "buttonCW5" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite CW move 5° relative}
    }
    vTcl:copy_lock $site_4_0.but54
    button "$site_4_0.but55" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonRot(30)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "30" 
    vTcl:DefineAlias "$site_4_0.but55" "buttonCW30" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite CW move 30° relative}
    }
    vTcl:copy_lock $site_4_0.but55
    button "$site_4_0.but56" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonRot(90)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "90" 
    vTcl:DefineAlias "$site_4_0.but56" "buttonCW90" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but56 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Immedite CW move 90° relative}
    }
    vTcl:copy_lock $site_4_0.but56
    button "$site_4_0.but98" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_buttonHome('ROT')" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -overrelief raised -pady 0 -text "Home" 
    vTcl:DefineAlias "$site_4_0.but98" "buttonRotHome" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_0.but53 \
        -in $site_4_0 -x 10 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but54 \
        -in $site_4_0 -x 60 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but55 \
        -in $site_4_0 -x 110 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but56 \
        -in $site_4_0 -x 160 -y 20 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but98 \
        -in $site_4_0 -x 80 -y 60 -width 60 -relwidth 0 -height 24 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab62
    button "$site_3_0.but63" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_stop" -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "STOP" 
    vTcl:DefineAlias "$site_3_0.but63" "buttonRotStop" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.but63
    place $site_3_0.lab48 \
        -in $site_3_0 -x 10 -y 20 -width 220 -relwidth 0 -height 101 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 320 -y 20 -width 220 -height 101 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but63 \
        -in $site_3_0 -x 240 -y 30 -width 70 -relwidth 0 -height 60 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.lab67
    menu "$top.m70" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground black -background $vTcl(actual_gui_menu_bg) \
        -font "{Segoe UI} 9" -foreground black -tearoff 0 
### SPOT dump_widget_opt A
    labelframe "$top.lab76" \
        \
        -font "-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -relief flat -text "Waypoints" \
        -background $vTcl(actual_gui_bg) -height 135 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 450 
    vTcl:DefineAlias "$top.lab76" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.lab76
    frame "$site_3_0.fra78" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 115 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 117 
    vTcl:DefineAlias "$site_3_0.fra78" "Frame1_1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.fra78
    button "$site_4_0.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -command "lambda :cb_waypoint(1, self.set1_pos, self.set1_rot)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Set 1" 
    vTcl:DefineAlias "$site_4_0.but50" "buttonSetWp1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Set a waypoint at the location below}
    }
    vTcl:copy_lock $site_4_0.but50
    entry "$site_4_0.ent51" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable "set1_pos" -width 44 
    vTcl:DefineAlias "$site_4_0.ent51" "EntryPosWp1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.ent51
    entry "$site_4_0.ent52" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable "set1_rot" -width 44 
    vTcl:DefineAlias "$site_4_0.ent52" "EntryRotWp1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.ent52
    label "$site_4_0.lab64" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Position" 
    vTcl:DefineAlias "$site_4_0.lab64" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.lab64
    label "$site_4_0.lab65" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Rotation" 
    vTcl:DefineAlias "$site_4_0.lab65" "Label3_1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.lab65
    button "$site_4_0.but66" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -command "lambda :cb_go(1, self.set1_pos, self.set1_rot)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Go" 
    vTcl:DefineAlias "$site_4_0.but66" "ButtonSetWp1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.but66
    place $site_4_0.but50 \
        -in $site_4_0 -x 33 -y 5 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent51 \
        -in $site_4_0 -x 5 -y 50 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent52 \
        -in $site_4_0 -x 55 -y 50 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab64 \
        -in $site_4_0 -x 5 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab65 \
        -in $site_4_0 -x 55 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.but66 \
        -in $site_4_0 -x 5 -y 75 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.fra78
    frame "$site_3_0.fra79" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 115 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 117 
    vTcl:DefineAlias "$site_3_0.fra79" "Frame1_2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.fra79
    button "$site_4_0.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -command "lambda :cb_waypoint(2, self.set2_pos, self.set2_rot)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Set 2" 
    vTcl:DefineAlias "$site_4_0.but50" "buttonSetWp2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Set a waypoint at the location below}
    }
    vTcl:copy_lock $site_4_0.but50
    entry "$site_4_0.ent51" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable "set2_pos" -width 44 
    vTcl:DefineAlias "$site_4_0.ent51" "EntryPosWp2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.ent51
    entry "$site_4_0.ent52" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable "set2_rot" -width 44 
    vTcl:DefineAlias "$site_4_0.ent52" "EntryRotWp2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.ent52
    label "$site_4_0.lab64" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Position" 
    vTcl:DefineAlias "$site_4_0.lab64" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.lab64
    label "$site_4_0.lab65" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Rotation" 
    vTcl:DefineAlias "$site_4_0.lab65" "Label3_2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.lab65
    button "$site_4_0.but66" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -command "lambda :cb_go(2, self.set2_pos, self.set2_rot)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Go" 
    vTcl:DefineAlias "$site_4_0.but66" "ButtonSetWp2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.but66
    place $site_4_0.but50 \
        -in $site_4_0 -x 33 -y 5 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent51 \
        -in $site_4_0 -x 5 -y 50 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent52 \
        -in $site_4_0 -x 55 -y 50 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab64 \
        -in $site_4_0 -x 5 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab65 \
        -in $site_4_0 -x 55 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.but66 \
        -in $site_4_0 -x 5 -y 75 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.fra79
    frame "$site_3_0.fra80" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 115 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 117 
    vTcl:DefineAlias "$site_3_0.fra80" "Frame1_3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.fra80
    button "$site_4_0.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -command "lambda :cb_waypoint(3, self.set3_pos, self.set3_rot)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Set 3" 
    vTcl:DefineAlias "$site_4_0.but50" "buttonSetWp3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Set a waypoint at the location below}
    }
    vTcl:copy_lock $site_4_0.but50
    entry "$site_4_0.ent51" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable "set3_pos" -width 44 
    vTcl:DefineAlias "$site_4_0.ent51" "EntryPosWp3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.ent51
    entry "$site_4_0.ent52" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable "set3_rot" -width 44 
    vTcl:DefineAlias "$site_4_0.ent52" "EntryRotWp3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.ent52
    label "$site_4_0.lab64" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Position" 
    vTcl:DefineAlias "$site_4_0.lab64" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.lab64
    label "$site_4_0.lab65" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Rotation" 
    vTcl:DefineAlias "$site_4_0.lab65" "Label3_3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.lab65
    button "$site_4_0.but66" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -command "lambda :cb_go(3, self.set3_pos, self.set3_rot)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Go" 
    vTcl:DefineAlias "$site_4_0.but66" "ButtonSetWp3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.but66
    place $site_4_0.but50 \
        -in $site_4_0 -x 33 -y 5 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent51 \
        -in $site_4_0 -x 5 -y 50 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent52 \
        -in $site_4_0 -x 55 -y 50 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab64 \
        -in $site_4_0 -x 5 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab65 \
        -in $site_4_0 -x 55 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.but66 \
        -in $site_4_0 -x 5 -y 75 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.fra80
    frame "$site_3_0.fra81" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 115 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 117 
    vTcl:DefineAlias "$site_3_0.fra81" "Frame1_4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.fra81
    button "$site_4_0.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -command "lambda :cb_waypoint(4, self.set4_pos, self.set4_rot)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Set 4" 
    vTcl:DefineAlias "$site_4_0.but50" "buttonSetWp4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $site_4_0.but50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Set a waypoint at the location below}
    }
    vTcl:copy_lock $site_4_0.but50
    entry "$site_4_0.ent51" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable "set4_pos" -width 44 
    vTcl:DefineAlias "$site_4_0.ent51" "EntryPosWp4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.ent51
    entry "$site_4_0.ent52" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable "set4_rot" -width 44 
    vTcl:DefineAlias "$site_4_0.ent52" "EntryRotWp4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.ent52
    label "$site_4_0.lab64" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Position" 
    vTcl:DefineAlias "$site_4_0.lab64" "Label2_4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.lab64
    label "$site_4_0.lab65" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Rotation" 
    vTcl:DefineAlias "$site_4_0.lab65" "Label3_4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.lab65
    button "$site_4_0.but66" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -command "lambda :cb_go(4, self.set4_pos, self.set4_rot)" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Go" 
    vTcl:DefineAlias "$site_4_0.but66" "ButtonSetWp4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.but66
    place $site_4_0.but50 \
        -in $site_4_0 -x 33 -y 5 -width 47 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent51 \
        -in $site_4_0 -x 5 -y 50 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent52 \
        -in $site_4_0 -x 55 -y 50 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab64 \
        -in $site_4_0 -x 5 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab65 \
        -in $site_4_0 -x 55 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.but66 \
        -in $site_4_0 -x 5 -y 75 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.fra81
    place $site_3_0.fra78 \
        -in $site_3_0 -x 10 -y 20 -width 110 -height 110 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra79 \
        -in $site_3_0 -x 120 -y 20 -width 110 -height 110 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra80 \
        -in $site_3_0 -x 230 -y 20 -width 110 -height 110 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra81 \
        -in $site_3_0 -x 340 -y 20 -width 110 -height 110 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.lab76
    labelframe "$top.lab84" \
        \
        -font "-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -text "Load Program File" \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 540 
    vTcl:DefineAlias "$top.lab84" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.lab84
    label "$site_3_0.lab85" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "File Name" 
    vTcl:DefineAlias "$site_3_0.lab85" "Label5" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.lab85
    entry "$site_3_0.ent86" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable "filepath" -width 454 
    vTcl:DefineAlias "$site_3_0.ent86" "EntryFile" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.ent86
    button "$site_3_0.but87" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_cancel_file" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Cancel" 
    vTcl:DefineAlias "$site_3_0.but87" "ButtonCancelFile" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.but87
    button "$site_3_0.but88" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -command "lambda :cb_openFile(filepath)" -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Open" 
    vTcl:DefineAlias "$site_3_0.but88" "ButtonOpenFile" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.but88
    button "$site_3_0.but89" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_run_program" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -state disabled -text "Run" 
    vTcl:DefineAlias "$site_3_0.but89" "ButtonRunProg" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.but89
    button "$site_3_0.but90" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "cb_step_program" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -state disabled -text "Step" 
    vTcl:DefineAlias "$site_3_0.but90" "ButtonStepProg" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.but90
    button "$site_3_0.but96" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "..." 
    vTcl:DefineAlias "$site_3_0.but96" "ButtonSelectFile" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.but96
    place $site_3_0.lab85 \
        -in $site_3_0 -x 10 -y 20 -width 64 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent86 \
        -in $site_3_0 -x 70 -y 20 -width 420 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but87 \
        -in $site_3_0 -x 340 -y 45 -width 50 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but88 \
        -in $site_3_0 -x 430 -y 45 -width 50 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but89 \
        -in $site_3_0 -x 70 -y 45 -width 50 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but90 \
        -in $site_3_0 -x 140 -y 45 -width 50 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but96 \
        -in $site_3_0 -x 490 -y 20 -width 30 -relwidth 0 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.lab84
    labelframe "$top.lab93" \
        \
        -font "-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -relief flat -text "GCode" \
        -background $vTcl(actual_gui_bg) -height 165 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 210 
    vTcl:DefineAlias "$top.lab93" "Labelframe5" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.lab93
    vTcl::widgets::ttk::scrolledtext::CreateCmd "$site_3_0.scr95" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr95" "Scrolledtext1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A

    $site_3_0.scr95.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -relief flat \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl:copy_lock $site_3_0.scr95
    place $site_3_0.scr95 \
        -in $site_3_0 -x 5 -y 25 -width 195 -relwidth 0 -height 135 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.lab93
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab47 \
        -in $top -x 20 -y 10 -width 550 -relwidth 0 -height 135 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 470 -y 300 -width 110 -relwidth 0 -height 110 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 20 -y 145 -width 550 -height 135 -anchor nw \
        -bordermode ignore 
    place $top.lab76 \
        -in $top -x 5 -y 285 -width 450 -relwidth 0 -height 135 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab84 \
        -in $top -x 20 -y 600 -width 540 -relwidth 0 -height 75 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab93 \
        -in $top -x 20 -y 430 -width 210 -relwidth 0 -height 165 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}
proc cb_scaleLinSpeed {args} { }
proc cb_scaleRotSpeed {args} { }

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

